https:
  port: "8082"

api:
  account:
    host: "nto-account-api-sfdc-v1.us-e2.cloudhub.io"
    port: "443"
    

anypoint:
  platform:
    client_id: "c7ee6e3c19f4407b964a5bd95f8e846e"
    client_secret: "0874121A1d584e419e86F1360333Ca55"
    visualizer:
      layer: "Process"  

app:
  client_id: "76a81264c2464d30bb777494f778378a"
  client_secret: "c361203e7e8d48419B81BF2AbAC7645B"
  autodiscovery: "15527339"
  
keystore:
  path: "docker01.domain.local.jks"
  password: "Welcome1"